### ISSUE TITLE
ISSUE: Template error in reset_codeslot script

### ISSUE THREAD

**Issue by firstof9** [FutureTense/keymaster#233]
**Describe the bug**
Template error in latest Home Assistant beta.

**Environment (please complete the following information):**

- OS: Ubuntu
- Type of system that HA is running on: x86_64
- Home Assistant version: 2021.10.0b0
- Hassio/Docker/Core? Container
- Component version: 0.0.63
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset 910

**Logs**
```
Template warning: 'timestamp_custom' got invalid input '00:00' when compiling template '{{ '00:00' | timestamp_custom('%H:%M') }}' but no default was specified. Currently 'timestamp_custom' will return '00:00', however this template will fail to render in Home Assistant core 2021.12
```

**Screenshots**
n/a

**Additional context**
Lines 85-92 in `keymaster_common_child.yaml`:
```yaml
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_start_date_LOCKNAME_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_end_date_LOCKNAME_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
```

Likely similar in `keymaster_common.yaml`

**Comment by FutureTense** [comment]
This might be due to a change in core.

https://community.home-assistant.io/t/template-changes-i-dont-understand/344586/3

**Comment by firstof9** [comment]
It was, I merged a fix for it tho.

**Comment by FutureTense** [comment]
I’m still getting the error in the log

**Comment by nholben** [comment]
Still getting this error.

Template warning: 'timestamp_custom' got invalid input '00:00' when compiling template '{{ '00:00' | timestamp_custom('%H:%M') }}' but no default was specified. Currently 'timestamp_custom' will return '00:00', however this template will fail to render in Home Assistant core 2022.1

**Comment by firstof9** [comment]
Regenerate your files.
