### ISSUE TITLE
ISSUE: Beta Reconfigure does not work

### ISSUE THREAD

**Issue by tykeal** [FutureTense/keymaster#462]
**Describe the bug**
The reconfigure flow does not properly work.

First none of the entity name strings or helper text is showing up from the initial configuration flow (missing strings.json data for reconfigure)

The lock that is configured is not showing up in the lock_entity_id (this is a call back to issue #455) because of this it is impossible to reconfigure the flow again due to the missing lock

Additionally, all of the various sensor / notify selections that do not get filled in with their prior configuration forcing reselection of them. To be specific:

`sensorname` (the door sensor)
`alarm_level_of_user_code_entity_id`
`alarm_type_or_access_control_entity_id`
`notify_script`

All of these were set to none (the default) during configuration but failed to repopulate for the configuration screen.

**Environment (please complete the following information):**

- OS: Home Assistant OS
- Type of system that HA is running on: Home Assistant Yellow
- Home Assistant version: 2025.8.1
- Hassio/Docker/Core? Hassio
- Component version: v0.1.0-b1 commit e570f803b4bf089e3fbd544a95f64e51c600d15c
- Z-Wave integration name: ZWave-JS UI
- Lock make and model: Kwikset 914

**Logs**
Nothing in the logs, I'm running keymaster in debug mode but this is all happening in HA itself before being handed back to the integration for validation and processing.

**Screenshots**
Initial reconfigure screen. Yes, there is a lock listed there but that is not the ZWave lock that is being managed but a WiFi Schlage Encode that is also on my test rig.

<img width="395" height="910" alt="Image" src="https://github.com/user-attachments/assets/e295ff10-6cf8-4a50-987f-d8787a27facb" />

Trying to save without selecting the lock. The lock that _should_ be selected has entityID of lock.zwavetestlock but is not not in the pick list.
<img width="397" height="913" alt="Image" src="https://github.com/user-attachments/assets/79a87c90-9d7d-4a6f-bd77-a00a1e50bdb8" />

**Comment by firstof9** [comment]
Thanks, I'll get the reconfig flow sorted.
Your report is very helpful. Cheers.

**Comment by tykeal** [comment]
@firstof9 so, I think I found part of the reason why the reconfig flow wasn't showing me the lock. Deleting a keymaster lock (even if it's the last one) doesn't fully purge the json data cache right away. it takes a full coordinator update cycle before the lock gets fully purged. Somewhere in my testing I had restarted my test instance fairly quickly after deleting my keymaster configuration and the json cache for the lock was sticking around.

After fully purging the cache that has made it so that the lock will show up during the reconfigure flow, it wasn't showing up previously because that cache was causing 2 configurations using the lock entity_id to exist and so the `_get_locks_in_use` was still returning one instance of the lock for the exclusion.

I see you've got a PR open to hopefully fix the flow fixed, but at least one of the issues was that. It's very likely that could be a root cause issue related to other people not being able to see some locks, particularly after a failed or partial migration!

**Comment by tykeal** [comment]
Follow on, this might be the root cause of some of the issues, I just looked at my HA instance where I've completely removed all keymaster configuration and I've still got 3 cached configurations and they are all for locks that have gone AWOL for me!

**Comment by firstof9** [comment]
Interesting findings, I've merged the reconfig fix, I noticed I forgot to update the translations as well so all the labels should be fixed.

**Comment by tykeal** [comment]
> Interesting findings, I've merged the reconfig fix, I noticed I forgot to update the translations as well so all the labels should be fixed.

Well, the new beta refuses to load. I'm getting the following in the log:

```
2025-08-14 15:29:10.444 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'keymaster' does not have a valid version key () in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

**Comment by tykeal** [comment]
The manifest got an empty string for the version for some reason. Did you not have it tagged before you did the publish?

**Comment by firstof9** [comment]
It was tagged. I think I need to update the workflow.

**Comment by tykeal** [comment]
I don't think this caused it but the only changes to that file were `yamllint` stanzas put in by me ☹️

**Comment by firstof9** [comment]
Nah there was a deprecated method in the workflow on `main`, I have to update all my repos accordingly as well.
The release has been fixed.

**Comment by tykeal** [comment]
FYI still can't complete the reconfigure. I get a `keymaster Lock Name already in use` error when I try to save it even if I make no changes (other than selecting none for all the things that didn't auto-populate)

**Comment by tykeal** [comment]
At least all the strings are there now! 🥇

**Comment by firstof9** [comment]
> I get a `keymaster Lock Name already in use` error

Ok I know how to fix that, I'll do a PR for it tomorrow.

**Comment by tykeal** [comment]
This was fixed with #465 & #468
