### ISSUE TITLE
ISSUE: Some Schlage lock user/pin slots stuck "Adding" or "Deleting" - Sync actually OK

### ISSUE THREAD

**Issue by bjh45964** [FutureTense/keymaster#520]
After updating to v0.1.1-b1, the pin/user slots on my parent lock and one other lock are stuck adding and deleting (adding for slots with pin set, deleting for slots with no pin set)

I have a mix of Schlage BE468, BE469 and BE469ZP. 6 locks, one configured as parent to the other 5.

First off, the sync seems to work WAY better since 1.0. The locks get to a steady state quicker, and it seems like codes sync better though I've still had at least one slot report as synced when it wasn't.

I have 2 ZWave JS UI instances attached to HomeAssistant: 1. HA integrated with Zooz ZST10 700(ZWAVE1), 2. RPI bridge device running ZWave JS UI docker image with Nabu Casa ZWA-2(ZWAVE2).

Each Zwave controller has a 468, 469 and 469ZP connected to it. (This wasn't planned, just turned out that way)

Each time I've reconfigured to test, I remove all locks from Keymaster, then remove the HACS Keymaster download, re-download beta, re-add locks. I have NOT tried removing/re-adding them from Zwave controller.

I've tried 3 full rebuilds using different locks as the parents, and I end up with a unpredictable failure of PIN codes sync status failure. It doesn't appear completely random. I have one lock that hasn't yet properly shown sync status. The status of "synced" seems to be more consistent. The status of "deleting" or "disconnected" for unconfigured slots is hit or miss.

- OS: HassOS
- Type of system that HA is running on: TrueNas Scale VM
- Component version: v0.1.1-b1
- Z-Wave integration name: ZWaveJS UI
- Lock make and model: Schlage BE468, BE469, BE469ZP
- Installation method
Home Assistant OS
Core: 2025.11.1
Supervisor: 2025.11.2
Operating System: 16.3
Frontend: 20251105.0

**Comment by firstof9** [comment]
Enable debug logging and check your log for errors or loops.

**Comment by bjh45964** [comment]
Having trouble copy log data out, but I'm seeing this for all slots when deleting and re-adding the consistently problematic lock:

2025-11-12 11:09:05.930 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 1: Unable to clear PIN. NotFoundError: userIdStatus for code slot 1 not found. This happens for each pin slot.

I also see a recurring debug event for 'update_lock_data', where the problem door has an empty set (just []), and the working locks all have a valid JSON string.

I think I'm running into an unrelated bug, deleting the lock doesn't appear to complete, but that's a different issue. I don't think it would have been a factor when I completely removed the Keymaster integration.

**Comment by irishpadres** [comment]
I have 2 locks that are children of a parent lock that just stay in Adding. I enabled debug logs and has the following:
This error originated from a custom integration.

```
Logger: custom_components.keymaster.coordinator
Source: helpers/update_coordinator.py:403
integration: keymaster (documentation, issues)
First occurred: 12:33:12 PM (3 occurrences)
Last logged: 12:35:31 PM

Unexpected error fetching keymaster data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 403, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/keymaster/coordinator.py", line 1733, in _async_update_data
    await self._update_lock_data(keymaster_config_entry_id=keymaster_config_entry_id)
  File "/config/custom_components/keymaster/coordinator.py", line 1795, in _update_lock_data
    await self._update_code_slots(kmlock=kmlock, usercodes=usercodes)
  File "/config/custom_components/keymaster/coordinator.py", line 1820, in _update_code_slots
    await self._update_slot(kmlock=kmlock, kmslot=kmslot, code_slot_num=code_slot_num)
  File "/config/custom_components/keymaster/coordinator.py", line 1836, in _update_slot
    await self.clear_pin_from_lock(
    ...<3 lines>...
    )
  File "/config/custom_components/keymaster/coordinator.py", line 1415, in clear_pin_from_lock
    await clear_usercode(kmlock.zwave_js_lock_node, code_slot_num)
  File "/usr/local/lib/python3.13/site-packages/zwave_js_server/util/lock.py", line 173, in clear_usercode
    return await node.async_set_value(value, CodeSlotStatus.AVAILABLE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zwave_js_server/model/node/__init__.py", line 568, in async_set_value
    return SetValueResult(result["result"])
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.13/site-packages/zwave_js_server/model/value.py", line 436, in __post_init__
    self.status = SetValueStatus(self.data["status"])
                                 ~~~~~~~~~^^^^^^^^^^
KeyError: 'status'
```

**Comment by bjh45964** [comment]
> I have 2 locks that are children of a parent lock that just stay in Adding. I enabled debug logs and has the following: This error originated from a custom integration.

Are you running Keymaster v0.1.1-b1? What kind of locks are these?

**Comment by firstof9** [comment]
> This error originated from a custom integration.

This is an error from zwave_js, looks like your locks didn't interview fully or something, try refreshing the UserCodes command class via Zwave JS UI.

**Comment by jshessen** [comment]
I had a similar issue where some locks had limited connectivity, and although the command to clear the code "worked" they would enter a death spiral of retries flooding the mesh, and even causing the controller to have issues.

The PR I submitted operates on the notion that if the parent is "disabled" we treat it as None which eliminates the retry logic.

Before:
````python
child_pin = child_kmlock.code_slots[code_slot_num].pin
pin_mismatch = kmslot.pin != child_pin and not (
    child_pin and "*" in child_pin
)
````
After:

```python
child_pin = child_kmlock.code_slots[code_slot_num].pin

# If parent slot is disabled or inactive, treat parent PIN as None for comparison
# to prevent endless clear loops when parent still has PIN in memory
parent_pin_for_comparison = (
    kmslot.pin if (kmslot.enabled and kmslot.active) else None
)

pin_mismatch = parent_pin_for_comparison != child_pin and not (
    child_pin and "*" in child_pin
)
```
This prevents false mismatch detection when parent slots are disabled but retain PIN values in memory.

**Comment by bjh45964** [comment]
That makes sense. In my particular case, none of the parent code slots are disabled, so I don't think this is the issue I'm running into.

**Comment by jshessen** [comment]
@bjh45964 -- my issue happened both ways ... when I enabled a new code it would work for some locks perfectly, but then if it set the code but timed out in response ... the lock would hang in the "Adding" ... if I disabled to clear the code same pattern, but it would hang in the "Deleting"

not saying it is 100% the same issue, but with this code in place I can now add and delete PINs without the retry loop taking down my mesh

**Comment by bjh45964** [comment]
Got it. I'll certainly test as soon as your change gets released.

**Comment by firstof9** [comment]
`v0.1.1-b2` has been packed. Give it a try.

**Comment by bjh45964** [comment]
Applied b2, parent lock then failed to load with:

```
[36m2025-11-12 14:40:23.065 DEBUG (MainThread) [custom_components.keymaster.coordinator] [async_setup] Imported 6 keymaster locks[0m
[31m2025-11-12 14:40:23.066 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry parent_door for keymaster
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/keymaster/__init__.py", line 98, in async_setup_entry
    await async_setup_services(hass)
  File "/config/custom_components/keymaster/services.py", line 33, in async_setup_services
    await coordinator.initial_setup()
  File "/config/custom_components/keymaster/coordinator.py", line 135, in initial_setup
    await self._async_setup()
  File "/config/custom_components/keymaster/coordinator.py", line 151, in _async_setup
    await self._rebuild_lock_relationships()
  File "/config/custom_components/keymaster/coordinator.py", line 476, in _rebuild_lock_relationships
    self.kmlocks[
    ~~~~~~~~~~~~^
        child_config_entry_id
        ^^^^^^^^^^^^^^^^^^^^^
    ].child_config_entry_ids.remove(child_config_entry_id)
    ^
KeyError: 'XXX'[0m
```

Trying to rollback to b1, if that doesn't work I'll reinstall with b2 and see if it works from a clean install

**Comment by jshessen** [comment]
@bjh45964 -- I think I can see the error in how the key is referenced ... I am trying to run through testing to validate ... once I have that fully vetted, I can try to submit a new PR

**Comment by bjh45964** [comment]
Will test once it's out there.

Just a note, I'm not aware of any orphaned locks during my update from b1 to b2, unless there are entity/integration IDs that are persistent across removal of integrations and entire HACS elements. I have recently completely (as far as I know) cleared out my Keymaster config and rebuilt, as part of testing before submitting my original issue.

**Comment by bjh45964** [comment]
I just tried a fresh install of b2 and can confirm the child lock issue crops up even with just 2 locks. As soon as I deleted the child lock, the parent lock broke.

**Comment by firstof9** [comment]
`v0.1.1-b3` packaged.

**Comment by jshessen** [comment]
Just as an FYI from my testing of b3

#### Deletion Test (2025-11-13 08:44:23)

**Action**: Deleted Garage Entry Lock (child lock) through Home Assistant UI

**Expected Behavior** (with fix):

- Lock deletion triggers `_rebuild_lock_relationships()`
- Orphaned child reference removed from parent's list
- No KeyError exception

**Observed Results**:

```log
2025-11-13 08:44:23.767 DEBUG [delete_lock_by_config_entry_id] Garage Entry Lock: Scheduled to delete at 2025-11-13 08:44:33
2025-11-13 08:44:38.768 DEBUG [delete_lock] Garage Entry Lock: Triggered
2025-11-13 08:44:38.768 DEBUG [delete_lock] Garage Entry Lock: Deleting
2025-11-13 08:44:38.775 DEBUG JSON File Updated
2025-11-13 08:44:38.780 DEBUG Finished fetching keymaster data in 0.005 seconds (success: True)
```

**Result**: ✅ **PASS** - Lock deleted cleanly without KeyError

#### Re-Addition Test (2025-11-13 08:46:06)

**Action**: Added Garage Entry Lock back through Home Assistant UI

**Expected Behavior**:

- Lock re-added to system
- Parent-child relationships rebuilt
- Code slots synchronized between parent and child

**Observed Results**:

```log
2025-11-13 08:46:06.876 DEBUG Garage Entry Lock: usercodes discovered
2025-11-13 08:46:09.502 DEBUG [set_pin_on_lock] Garage Entry Lock: Code Slot 1: Setting PIN to 1111
2025-11-13 08:46:09.502 DEBUG [_sync_child_locks] Garage Entry Lock Slot 1: parent=1111 child=1111 mismatch=False
[All 10 code slots synced successfully]
2025-11-13 08:46:09.518 DEBUG JSON File Updated
2025-11-13 08:46:09.518 DEBUG Finished fetching keymaster data in 2.643 seconds (success: True)
```

**Result**: ✅ **PASS** - Lock re-added successfully, all code slots synchronized with parent

### Comparison to Original Bug

**Before Fix (2025-11-07 13:39:31)** - Same system running v0.1.1-b1:

```log
File "/config/custom_components/keymaster/coordinator.py", line 1300, in _delete_lock
  await self._rebuild_lock_relationships()
File "/config/custom_components/keymaster/coordinator.py", line 476, in _rebuild_lock_relationships
KeyError: '01K9E1FNZPAWQW99X434BPYN80'
```

**After Fix (2025-11-13 08:44:38)** - Same system running v0.1.1-b3:

```log
[delete_lock] Garage Entry Lock: Deleting
JSON File Updated
Finished fetching keymaster data in 0.005 seconds (success: True)
```

**Comment by bjh45964** [comment]
Updated to b3 and was able to remove and re-add one of the problem locks without fail. Unfortunately, the adding/deleting behavior is still an issue.


```
[36m2025-11-13 06:59:05.634 DEBUG (MainThread) [custom_components.keymaster.coordinator] [connect_and_update_lock] problem_door: Lock connected, updating Device and Nodes[0m
[36m2025-11-13 06:59:05.635 DEBUG (MainThread) [custom_components.keymaster.coordinator] [connect_and_update_lock] problem_door: node_status: 4[0m
[36m2025-11-13 06:59:05.635 DEBUG (MainThread) [custom_components.keymaster.coordinator] [update_lock_data] problem_door: usercodes: [][0m
[36m2025-11-13 06:59:05.635 DEBUG (MainThread) [custom_components.keymaster.coordinator] [clear_pin_from_lock] problem_door: Code Slot 1: Clearing PIN[0m
[31m2025-11-13 06:59:05.635 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 1: Unable to clear PIN. NotFoundError: userIdStatus for code slot 1 not found[0m
[36m2025-11-13 06:59:05.635 DEBUG (MainThread) [custom_components.keymaster.coordinator] [clear_pin_from_lock] problem_door: Code Slot 2: Clearing PIN[0m
[31m2025-11-13 06:59:05.635 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 2: Unable to clear PIN. NotFoundError: userIdStatus for code slot 2 not found[0m
[36m2025-11-13 06:59:05.635 DEBUG (MainThread) [custom_components.keymaster.coordinator] [clear_pin_from_lock] problem_door: Code Slot 3: Clearing PIN[0m
[31m2025-11-13 06:59:05.635 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 3: Unable to clear PIN. NotFoundError: userIdStatus for code slot 3 not found[0m
[36m2025-11-13 06:59:05.636 DEBUG (MainThread) [custom_components.keymaster.coordinator] [clear_pin_from_lock] problem_door: Code Slot 4: Clearing PIN[0m
[31m2025-11-13 06:59:05.636 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 4: Unable to clear PIN. NotFoundError: userIdStatus for code slot 4 not found[0m
[36m2025-11-13 06:59:05.636 DEBUG (MainThread) [custom_components.keymaster.coordinator] [clear_pin_from_lock] problem_door: Code Slot 5: Clearing PIN[0m
[31m2025-11-13 06:59:05.637 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 5: Unable to clear PIN. NotFoundError: userIdStatus for code slot 5 not found[0m
[36m2025-11-13 06:59:05.637 DEBUG (MainThread) [custom_components.keymaster.coordinator] [clear_pin_from_lock] problem_door: Code Slot 6: Clearing PIN[0m
[31m2025-11-13 06:59:05.637 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 6: Unable to clear PIN. NotFoundError: userIdStatus for code slot 6 not found[0m
[36m2025-11-13 06:59:05.639 DEBUG (MainThread) [custom_components.keymaster.coordinator] [_sync_child_locks] problem_door Slot 1: parent=1234 (actual=1234, enabled=True) child=None mismatch=True[0m
[36m2025-11-13 06:59:05.639 DEBUG (MainThread) [custom_components.keymaster.coordinator] [set_pin_on_lock] problem_door: Code Slot 1: Setting PIN to 1234[0m
[31m2025-11-13 06:59:05.639 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 1: Unable to set PIN. NotFoundError: userCode for code slot 1 not found[0m
[36m2025-11-13 06:59:05.639 DEBUG (MainThread) [custom_components.keymaster.coordinator] [_sync_child_locks] problem_door Slot 2: parent=1235 (actual=1235, enabled=True) child=None mismatch=True[0m
[36m2025-11-13 06:59:05.639 DEBUG (MainThread) [custom_components.keymaster.coordinator] [set_pin_on_lock] problem_door: Code Slot 2: Setting PIN to 1235[0m
[31m2025-11-13 06:59:05.639 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 2: Unable to set PIN. NotFoundError: userCode for code slot 2 not found[0m
[36m2025-11-13 06:59:05.639 DEBUG (MainThread) [custom_components.keymaster.coordinator] [_sync_child_locks] problem_door Slot 3: parent=1236 (actual=1236, enabled=True) child=None mismatch=True[0m
[36m2025-11-13 06:59:05.639 DEBUG (MainThread) [custom_components.keymaster.coordinator] [set_pin_on_lock] problem_door: Code Slot 3: Setting PIN to 1236[0m
[31m2025-11-13 06:59:05.640 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 3: Unable to set PIN. NotFoundError: userCode for code slot 3 not found[0m
[36m2025-11-13 06:59:05.640 DEBUG (MainThread) [custom_components.keymaster.coordinator] [_sync_child_locks] problem_door Slot 4: parent=1237 (actual=1237, enabled=True) child=None mismatch=True[0m
[36m2025-11-13 06:59:05.640 DEBUG (MainThread) [custom_components.keymaster.coordinator] [set_pin_on_lock] problem_door: Code Slot 4: Setting PIN to 1237[0m
[31m2025-11-13 06:59:05.640 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 4: Unable to set PIN. NotFoundError: userCode for code slot 4 not found[0m
[36m2025-11-13 06:59:05.640 DEBUG (MainThread) [custom_components.keymaster.coordinator] [_sync_child_locks] problem_door Slot 5: parent=None (actual=None, enabled=True) child=None mismatch=False[0m
[36m2025-11-13 06:59:05.640 DEBUG (MainThread) [custom_components.keymaster.coordinator] [_sync_child_locks] problem_door Slot 6: parent=None (actual=None, enabled=True) child=None mismatch=False[0m
[36m2025-11-13 06:59:05.667 DEBUG (SyncWorker_0) [custom_components.keymaster.coordinator] [write_config_to_json] JSON File Updated[0m
[36m2025-11-13 06:59:05.669 DEBUG (MainThread) [custom_components.keymaster.coordinator] [schedule_quick_refresh_if_needed] Scheduling refresh in 15 seconds[0m
[36m2025-11-13 06:59:05.672 DEBUG (MainThread) [custom_components.keymaster.coordinator] Finished fetching keymaster data in 0.047 seconds (success: True)[0m
```

**Comment by firstof9** [comment]
> 2025-11-13 06:59:05.639 ERROR (MainThread) [custom_components.keymaster.coordinator] [Coordinator] problem_door: Code Slot 1: Unable to set PIN. NotFoundError: userCode for code slot 1 not found

Go into ZwaveJS UI and make sure your UserCode command class exists.
Example:
<img width="871" height="852" alt="Image" src="https://github.com/user-attachments/assets/170df8af-0b7c-4783-8442-bba585403946" />

If this command class isn't showing up you need to re-interview your lock.

**Comment by bjh45964** [comment]
User Code class isn't present on the two locks with sync issues. Re-interviewing . . .

**Comment by bjh45964** [comment]
Reinterview instantiated User Code v1 and fixed sync. Thank you! Is it possible to test for those classes during addition of a lock? Are there any locks that DON'T have user codes that are still manageable by Keymaster?

**Comment by irishpadres** [comment]
Just upgraded to v0.1.1-b2 and getting 500 errors:

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:481
First occurred: 3:14:25 PM (2 occurrences)
Last logged: 3:14:36 PM

Error handling request from 172.30.33.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 214, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 188, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 195, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 83, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1464, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1510, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 493, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/keymaster/config_flow.py", line 119, in async_step_reconfigure
    return await _start_config_flow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/config/custom_components/keymaster/config_flow.py", line 348, in _start_config_flow
    data_schema = _get_schema(
        hass=cls.hass,
    ...<3 lines>...
        flow=cls,
    )
  File "/config/custom_components/keymaster/config_flow.py", line 218, in _get_schema
    exclude_entities=_get_locks_in_use(
                     ~~~~~~~~~~~~~~~~~^
        hass=hass, exclude=_get_default(CONF_LOCK_ENTITY_ID)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/keymaster/config_flow.py", line 182, in _get_locks_in_use
    data.extend([kmlock.lock_entity_id for kmlock in coordinator.data.values()])
                                                     ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by irishpadres** [comment]
Before I saw the b3 update, I ended up blowing away my entire config, re-interviewed the locks, and re-did the setup with b3. So far, locks (including 2 child locks) are staying synced.

**Comment by firstof9** [comment]
> Are there any locks that DON'T have user codes that are still manageable by Keymaster?

What would be the point?

**Comment by bjh45964** [comment]
> > Are there any locks that DON'T have user codes that are still manageable by Keymaster?
> 
> What would be the point?

I couldn't think of any, was just confirming. My point was that ideally key master would throw a warning or block addition of locks that don't have the user code class. Ideal thing would be to show them grey'd/disabled in the physical lock picker, or at least have a flag of some sort (no user code slots) or something. That would give the user an indicator that something wasn't right at the zwave level, instead of them thinking there was a key master issue.

**Comment by bjh45964** [comment]
All that said, my issue is fixed. Thank you both so much for the effort!

**Comment by firstof9** [comment]
> Ideal thing would be to show them grey'd/disabled in the physical lock picker, or at least have a flag of some sort (no user code slots) or something.

It's expected zwavejs to do it's job and fully interview a lock, but sometimes weird things happen.

**Comment by jmwhite5** [comment]
Commenting here since my issue #532 was closed as duplicate. 

I upgraded to version 0.1.1 as requested, but the issue persists.  After rebooting Home Assistant, KeyMaster gets stuck with codes showing  "Deleting" status indefinitely. The lock goes into an infinite programming loop.  Details: I tried to disable the parent active code and it quickly went to "sync" state.  But other 2 child locks stayed in "Deleting" state for a long time.  When I went back to the parent, it was now also in "deleting" state.  

025-12-20 09:25:20.409 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 1 => 0
2025-12-20 09:25:20.413 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3 9285 => 
2025-12-20 09:25:20.691 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:22.899 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 1 => 0
2025-12-20 09:25:22.904 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3 9285 => 
2025-12-20 09:25:23.181 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:25.231 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 1 => 0
2025-12-20 09:25:25.236 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3 9285 => 
2025-12-20 09:25:25.516 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:27.435 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:27.438 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:25:29.000 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:29.006 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:25:30.477 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:30.480 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:25:33.616 INFO APP: ::ffff:127.0.0.1 GET /health/zwave 301 162 - 1.858 ms
2025-12-20 09:25:42.046 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:42.049 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:25:42.330 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:44.612 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:44.615 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:25:44.889 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:45.489 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:45.493 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:45.501 INFO Z-WAVE: [Node 139] Value updated: 113-0-Home Security-Motion sensor status 8 => 0
2025-12-20 09:25:45.560 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:45.565 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:45.588 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:45.593 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.323 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.327 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.351 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.356 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.383 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.386 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.407 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.410 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.440 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.444 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.467 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.470 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.512 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.516 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:50.720 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmType 0 => 0
2025-12-20 09:25:50.723 INFO Z-WAVE: [Node 139] Value updated: 113-0-alarmLevel 0 => 0
2025-12-20 09:25:51.154 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:54.719 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:54.724 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:25:55.851 INFO Z-WAVE: [Node 131] Is now dead
2025-12-20 09:25:55.877 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-0 0 => 0
2025-12-20 09:25:55.881 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-0  => 
2025-12-20 09:25:57.512 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:25:57.516 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:25:58.791 INFO Z-WAVE: [Node 131] Has returned from the dead
2025-12-20 09:26:00.340 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:00.344 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3 0000 => 0000
2025-12-20 09:26:03.761 INFO APP: ::ffff:127.0.0.1 GET /health/zwave 301 162 - 1.748 ms
2025-12-20 09:26:07.660 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:07.662 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:07.944 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:10.079 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:10.082 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:10.358 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:12.363 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:12.368 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:12.652 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:14.568 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:14.571 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:16.115 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:16.118 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:17.621 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:17.628 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:29.166 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:29.171 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:29.450 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:31.626 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:31.631 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:31.914 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:33.902 INFO APP: ::ffff:127.0.0.1 GET /health/zwave 301 162 - 1.408 ms
2025-12-20 09:26:33.977 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:33.980 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:34.264 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:36.159 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:36.162 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:37.706 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:37.714 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:39.141 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:39.147 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:50.797 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:50.806 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:51.070 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:53.220 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:53.224 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:53.497 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:55.547 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:55.551 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3 0000 => 
2025-12-20 09:26:55.836 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:57.767 INFO Z-WAVE: [Node 131] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:57.770 INFO Z-WAVE: [Node 131] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:26:59.310 INFO Z-WAVE: [Node 144] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:26:59.314 INFO Z-WAVE: [Node 144] Value updated: 99-0-userCode-3  => 0000
2025-12-20 09:27:00.789 INFO Z-WAVE: [Node 143] Value updated: 99-0-userIdStatus-3 0 => 0
2025-12-20 09:27:00.793 INFO Z-WAVE: [Node 143] Value updated: 99-0-userCode-3  => 0000

**Comment by firstof9** [comment]
@jmwhite5 try this, remove your child locks, let your zwave network calm down.
Re-add the child locks as non-child locks.
After a few minutes, reconfigure a single child to to be a child of the parent lock, see if it all syncs up.
If that works, move on to the next lock and switch it to child as well.

**Comment by jmwhite5** [comment]
I just followed your instructions:

- deleted both child locks
- added 1 back as a standalone
- verified that I could de-active the code in the parent (and I can't remember if I checked on the child too.)
- waited until everything stabilized
- created the parent/child relationship
- tried to deactivate 1 code on the parent.  The status went to Disconnected quickly on the parent.
- the child code went into a Deleting loop
- the parent de-activated code eventually when from Disconnected to Deleting.  So now both locks are in a loop trying to de-activate the code.
- When I re-activate the code (in the parent), the status very quickly goes to Synced (that means there's no connectivity issue).

So at this point, everything works when all codes are Enabled.  Deactivating a code just doesn't work for me.

**Comment by firstof9** [comment]
The plague that is Yale and Schlage...
